version: "3.9"

services:
  user-service:
    build: ./services/user-service-php
    container_name: user-service
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=users
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  enrichment-service:
    build: ./services/enrichment-service-node
    container_name: enrichment-service
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/enrichment
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_ENRICH_URL=http://localhost:8081
    depends_on:
      - user-service
      - enrichment-service
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres-data:
  mongo-data:
